In [18]:
import numpy as np
import matplotlib.pyplot as plt
import inspect

In [19]:
import importlib
import sys
sys.path.append('../')
from Utils.perturbationsnew import RBPIndividual, RBPIndividualNew1, RBPIndividualNew2, zeroPerturb, noisePerturb, blurPerturb
from Utils.models import *
from Utils.data import perturb, generateSynthetic, generateSyntheticPerturbReal,ReadTS

print(sys.path)


['/Users/gali/anaconda3/envs/LIMEtf/lib/python310.zip', '/Users/gali/anaconda3/envs/LIMEtf/lib/python3.10', '/Users/gali/anaconda3/envs/LIMEtf/lib/python3.10/lib-dynload', '', '/Users/gali/anaconda3/envs/LIMEtf/lib/python3.10/site-packages', '/Users/gali/anaconda3/envs/LIMEtf/lib/python3.10/site-packages/setuptools/_vendor', '../', '../', '../']


## Test important content removal (accuracy decrease)

### Load synthetic dataset and train CNN model 

In [33]:
x_train, y_train,x_test_original, y_test_original = ReadTS('CricketY')
y_train = y_train - 1
y_test_original = y_test_original - 1
print(x_train.shape)
print(y_train)

(390, 300, 1)
[ 1.  3.  2.  2.  4.  0.  7.  9.  3.  4.  9.  1.  8.  4.  4.  9.  6. 10.
  6.  4.  1.  2.  2.  6.  0.  8.  5.  7. 11.  3. 10.  9.  8.  6.  4.  5.
 10.  7.  7.  9.  9. 11.  6.  2.  3.  6.  0. 11. 10. 11. 11.  8.  9.  3.
  1.  4.  1.  6.  4.  6. 11.  3.  2. 11.  7.  2.  9.  3.  6.  6.  0.  3.
 10.  7.  5.  2.  5.  0.  4.  8.  9. 11. 10.  4.  8.  4.  7. 10.  8. 11.
  1.  4. 10.  9.  3.  3.  6.  9.  9.  8.  0.  5.  4.  9.  7. 10. 11.  8.
  4. 11.  0.  0. 11. 11.  4.  2.  1.  6.  8.  6.  5.  2.  0. 10.  1.  1.
  9. 10.  7. 10.  4.  7.  7. 11.  1.  2.  3.  9.  2.  6.  8.  5.  6.  2.
  8.  8.  3.  2. 11.  3.  5.  9.  0.  5.  0.  0.  0.  3.  4.  4. 11. 10.
 11.  9.  0.  2.  6. 11.  4.  8.  1.  5.  9. 11.  5. 10.  0.  0.  5.  5.
  4.  9.  9.  1.  3.  4. 10.  9. 11.  2.  3.  2.  0.  3.  4.  6.  8.  3.
  7.  2.  6.  7.  8. 11.  7.  6.  0.  9.  8.  5.  4.  1.  3.  9.  6.  4.
  0.  1.  6.  5.  7. 10.  3.  1.  4. 10.  7.  8.  5. 10.  1. 10. 11.  7.
  2.  6.  1.  4.  4.  8.  2.  3.  5. 

In [34]:
from sklearn.preprocessing import StandardScaler
def normalize(TS):
    # 获取原始数据集的形状
    original_shape = TS.shape
    
    # 将数据集reshape成二维数组
    TS_2d = TS.reshape(original_shape[0] , original_shape[1])
    
    # 初始化StandardScaler
    scaler = StandardScaler()
    
    # 对数据集进行标准化
    TS_normalized = scaler.fit_transform(TS_2d)
    
    # 将标准化后的数据集reshape回原始形状
    TS = TS_normalized.reshape(original_shape)
    
    return TS

x_train = normalize(x_train)
x_test_original = normalize(x_test_original)
print(x_train)

[[[ 0.76395937]
  [ 0.73633328]
  [ 0.98299782]
  ...
  [ 0.24789194]
  [ 0.24236887]
  [ 0.24657619]]

 [[-0.53869465]
  [-0.40487069]
  [-0.55319388]
  ...
  [-0.66187984]
  [-0.66843458]
  [-0.66360391]]

 [[ 0.67348101]
  [ 0.52468589]
  [ 0.72692282]
  ...
  [ 1.6691223 ]
  [ 1.52290119]
  [ 1.52755027]]

 ...

 [[ 0.47439437]
  [ 0.59786604]
  [ 0.48204727]
  ...
  [ 1.69007314]
  [ 1.69732912]
  [ 1.70613567]]

 [[-0.89067676]
  [-0.691681  ]
  [-1.0586737 ]
  ...
  [-1.68305609]
  [-1.68589033]
  [-1.67739208]]

 [[-0.10764922]
  [-0.24146336]
  [-0.41105556]
  ...
  [ 0.23232486]
  [ 0.23569501]
  [ 0.6101929 ]]]


In [22]:
model = make_CNN_model(x_train.shape[1:],num_classes = 12)
trained_model, history = train_CNN_model(model, x_train, y_train, epochs=100, batch_size=32)

Epoch 1/100
10/10 [==============================] - 1s 26ms/step - loss: 2.4956 - sparse_categorical_accuracy: 0.1538 - val_loss: 2.4780 - val_sparse_categorical_accuracy: 0.1538
Epoch 2/100
10/10 [==============================] - 0s 19ms/step - loss: 2.3201 - sparse_categorical_accuracy: 0.2853 - val_loss: 2.4672 - val_sparse_categorical_accuracy: 0.1282
Epoch 3/100
10/10 [==============================] - 0s 18ms/step - loss: 2.2363 - sparse_categorical_accuracy: 0.3045 - val_loss: 2.4620 - val_sparse_categorical_accuracy: 0.1410
Epoch 4/100
10/10 [==============================] - 0s 20ms/step - loss: 2.1714 - sparse_categorical_accuracy: 0.3077 - val_loss: 2.4618 - val_sparse_categorical_accuracy: 0.1154
Epoch 5/100
10/10 [==============================] - 0s 17ms/step - loss: 2.1124 - sparse_categorical_accuracy: 0.3718 - val_loss: 2.4685 - val_sparse_categorical_accuracy: 0.1410
Epoch 6/100
10/10 [==============================] - 0s 17ms/step - loss: 2.0732 - sparse_categorica

In [23]:
test_loss, test_acc = trained_model.evaluate(x_test_original, y_test_original)

print("Test accuracy", test_acc)
print("Test loss", test_loss)

13/13 [==============================] - 0s 5ms/step - loss: 1.4823 - sparse_categorical_accuracy: 0.4590
Test accuracy 0.45897436141967773
Test loss 1.4822789430618286


### Create perturbed test sets and calculate decrease in accuracy

In [24]:
print(y_test_original.shape)

(390,)


In [25]:
print(inspect.getsource(perturb))
print(inspect.signature(perturb))

def perturb(perturbation_strategy, ts, index0, index1, global_ts = []):
    if perturbation_strategy == 'RBP':
        return RBPIndividual(ts, index0, index1)
    if perturbation_strategy == 'zero':
        return zeroPerturb(ts, index0, index1)
    if perturbation_strategy == 'noise':
        return noisePerturb(ts, index0, index1)
    if perturbation_strategy == 'blur':
        return blurPerturb(ts, index0, index1)
    if perturbation_strategy == 'RBP1':
        return RBPIndividualNew1(global_ts, ts, index0, index1)    
    if perturbation_strategy == 'RBP2':
        return RBPIndividualNew2(global_ts, ts, index0, index1)    

(perturbation_strategy, ts, index0, index1, global_ts=[])


In [26]:
predictions_original = model.predict(x_test_original)
perturb_test_set = x_test_original.copy()
perturb_test_set = perturb_test_set.reshape(x_test_original.shape[0:2])

x_test_rbp = np.asarray([perturb('RBP',x,200,300) for x in perturb_test_set])
x_test_rbp = np.expand_dims(x_test_rbp, axis=-1)
predictions_rbp = model.predict(x_test_rbp)

pert1 = perturb('RBP1',perturb_test_set[0],200,300, global_ts = perturb_test_set)
x_test_new1 = np.asarray([perturb('RBP1',x,60,160, global_ts = perturb_test_set) for x in perturb_test_set])
x_test_new1 = np.expand_dims(x_test_new1, axis=-1)
predictions_new1 = model.predict(x_test_new1)

#x_test_new2 = np.asarray([perturb('RBP2',x,400,500, global_ts = perturb_test_set) for x in perturb_test_set])
#x_test_new2 = np.expand_dims(x_test_new2, axis=-1)
#predictions_new2 = model.predict(x_test_new2)

x_test_zero = np.asarray([perturb('zero',x,200,300) for x in perturb_test_set])
x_test_zero = np.expand_dims(x_test_zero, axis=-1)
predictions_zero = model.predict(x_test_zero)

x_test_noise = np.asarray([perturb('noise',x,200,300) for x in perturb_test_set])
x_test_noise = np.expand_dims(x_test_noise, axis=-1)
predictions_noise = model.predict(x_test_noise)

x_test_blur = np.asarray([perturb('blur',x,200,300) for x in perturb_test_set])
x_test_blur = np.expand_dims(x_test_blur, axis=-1)
predictions_blur = model.predict(x_test_blur)

13/13 [==============================] - 0s 4ms/step


In [35]:
def l2norm(perturb):
    # 计算两个数组之间的差
    difference = perturb - x_test_original
    
    # 计算差的平方
    squared_difference = np.square(difference)
    
    # 计算平方和，沿着特征维度（axis=1），因为每个时间序列样本是一行
    sum_of_squares = np.sum(squared_difference, axis=1)
    
    # 计算平方和的平方根，即l2范数
    l2_norms = np.sqrt(sum_of_squares)
    
    average_l2_norm = np.mean(l2_norms)
    
    # l2_norms现在是一个形状为(467,)的数组，其中每个元素代表
    # 对应时间序列样本之间的l2范数
    print(average_l2_norm)  # 输出: (467,)

l2norm(x_test_rbp)
l2norm(x_test_new1)
l2norm(x_test_zero)
l2norm(x_test_noise)
l2norm(x_test_blur)

8.239141124031118
10.600143258233262
9.523537269023088
22.264487458736603
4.596424258228867


In [9]:
def accuracy(predictions, labels):
    hits = 0
    for i in range(0,len(predictions)):
        if predictions[i] == labels[i]:
            hits += 1
    return hits/len(predictions)

In [10]:
original_accuracy = accuracy(np.argmax(predictions_original,axis=1), y_test_original)
rbp_accuracy = accuracy(np.argmax(predictions_rbp,axis=1), y_test_original)
new1_accuracy = accuracy(np.argmax(predictions_new1,axis=1), y_test_original)
#new2_accuracy = accuracy(np.argmax(predictions_new2,axis=1), y_test_original)
zero_accuracy = accuracy(np.argmax(predictions_zero,axis=1), y_test_original)
noise_accuracy = accuracy(np.argmax(predictions_noise,axis=1), y_test_original)
blur_accuracy = accuracy(np.argmax(predictions_blur,axis=1), y_test_original)

In [11]:
print(" Original Accuracy: " + str(original_accuracy) + "\n"+
    " RBP Accuracy: " + str(rbp_accuracy) + "\n"+
    " RBP1 Accuracy: " + str(new1_accuracy) + "\n"+
    #" RBP2 Accuracy: " + str(new2_accuracy) + "\n"+
      
    " Zero Accuracy: " + str(zero_accuracy) + "\n"+
    " Noise Accuracy: " + str(noise_accuracy) + "\n"+
    " Blur Accuracy: " + str(blur_accuracy) + "\n")

 Original Accuracy: 0.3641025641025641
 RBP Accuracy: 0.26666666666666666
 RBP1 Accuracy: 0.11794871794871795
 Zero Accuracy: 0.21794871794871795
 Noise Accuracy: 0.1
 Blur Accuracy: 0.30256410256410254



In [15]:
print(np.argmax(predictions_rbp,axis=1))

[ 3  3  3  3 10 10  3  3  3 10 10  3  4 10  3  4  3 10  3  3  3  3  3 10
  3 10 10 10 10  3  9  3  3  3  3  3  3  9  4  3  3  9 10 10  3  3 10  9
 10  9  1 10 10  9 10  3  4  9  3 10 10 10  9  3  3 10 10  1 10  4 10  3
  3  3  3  3  3 10  3  3  3  3  9  3  4 10  3 10  3  3  3 10 10  3  3 10
 10  3 10  3  3  9 10  4  3  3 10  3  3  3  3  9  3  3  3  3  3  9 10  3
  3  3 10  3  3  3  3 10  3  3  3 10 10  3 10  3  3  9 10  4 10  3  3  3
 10  3  3 10  3  9  3 10  9  3  3  3  9  3  3  3  1  9  3  3 10 10  3 10
 10  3  3 10  3 10 10  9  4  9  3  3 10  3  3  5  3  3  3  3  9 10  9  3
  1  9  3 10  3 10  9 10 10  3  3  3  3 10  3  9  9  3 10 10  3  3 10  4
  9  9 10 10  9  3  3  3 10  9  3  3  3 10  9  3 10 10 10 10 10  3  3  3
  3  9 10  3 10 10  3  3 10  3  3 10 10  4 10  3  3  3 10  9 10  3  3 10
  3 10  3 10 10 10 10  3  3  3  3 10  3 10 10 10  9 10  3  3  6  3  4 10
  3  9 10  3 10  3 10  9  3 10 10  3  3 10  9  5  4 10  3  3  3 10  3  9
 10  3  3  3 10  4  1  3  3  3  3  3  3  9 10 10  3